### ISSUE TITLE
[BUG] Banner deletes item in hand

### ISSUE THREAD

**Issue by AustinGoodrich** [HydrolienF/FlagsH#10]
Plugin Version: FlagsH v4.0.1
Server Version:  Folia version 1.20.6, build 4

When a player holds a banner in their off-hand and holds an item in their right hand, the item in their right hand gets deleted and no banner is removed from the off-hand.

Video: https://youtu.be/xwAa9sqCxYg

**Comment by HydrolienF** [comment]
Thanks for reporting it, I will fix it.

**Comment by HydrolienF** [comment]
@AustinGoodrich the bug have been fix on last release.
