### ISSUE TITLE
Unable to remove placed flags

### ISSUE THREAD

**Issue by Paniramix** [HydrolienF/FlagsH#12]
For some reason some of the places banners as a flag can NOT be removed

**Comment by HydrolienF** [comment]
Thanks for reporting this. Can you send a screenshot of an unremovable flag with hitbox enabled ?

**Comment by Paniramix** [comment]
Here are 2 screenshots of the flags in question.

![2024-07-08_11 22 32](https://github.com/HydrolienF/FlagsH/assets/19983842/8ec014bc-7a56-40ce-870f-0dfc7cb81b36)
![2024-07-08_11 20 12](https://github.com/HydrolienF/FlagsH/assets/19983842/fe30b5c5-73c0-4873-898c-68d153341146)

**Comment by HydrolienF** [comment]
Thanks.
They looks OK, so it's probably a flag data issue.

Did you remove some files inside `plugins/FlagsH/` ? Flag data are stored there. This data are needed to extends or remove existing flags.
Did your server crash after this flags have been placed ? Brutal interruption of the server might cause a failure in flags data save.
If you find some error in your server logs containing `fr.formiko.flagsh` please send it here, it will help me understand how the flags broke.

To remove the broken flags you can do:
- `/kill @e[type=Interaction]` (it remove the flags hitbox in loaded chunks.)
- `/kill @e[type=ItemDisplay]` (it remove the flag texture in loaded chunks.)

**Comment by Paniramix** [comment]
Hi,
I have not removed any files from the mentioned directorie.
Sadly I did not noticed the issue till yesterday and it might have occurred earlier. Back when the latest version of the plugin was release I failed to notice it needed java 21. The server at the time was using java 17 so it failed to load. That same day I switched to java 21 and thought it was solved.
I will look back in the logs to see if there is any mention of a fr.formiko.flagsh error, but sadly not in a position to do so at the current time.

Thanks to the given commands the flags have been removed

**Comment by HydrolienF** [comment]
If the plugin have failed to load it should not have lost any flag data, and data are concive to be readable even after an update of FlagsH.
Maybe logs will help me to understand.
No pressure about the logs, take your time.

`fr.formiko.flagsh` will be display if the server catch an unexpected exception from my plugin.
There is 2 logs that might show an error: `Error while saving flags.` and `Error while loading flags.`
And each time the plugin start (when the server is reloaded) it say how much flags have been found `FlagsH loaded x flags.` If there is 0 flags loaded after the first flag have been added, then an error occured before.

Thanks a lot helping me debuging the plugin.

**Comment by HydrolienF** [comment]
I found a way to reproduce the unbreakable flags, by killing the server process (As for a crash).
All the Flags placed between the last restart before crash and the crash are never saved to the disk, so when the server is reloaded this flags can't be found in flags data (which make them unbreakable).

**Comment by HydrolienF** [comment]
That would explain why some flags can't be remove while others can.

**Comment by HydrolienF** [comment]
Fixed version will be release when I will have test it enough & update to 1.21.4 at the same time.
@Paniramix thanks for your help to understand the issue.

**Comment by HydrolienF** [comment]
It's `/kill @e[type=minecraft:item_display]` now by the way
