### ISSUE TITLE
Banners On Switchable Blocks

### ISSUE THREAD

**Issue by Aylywyn** [HydrolienF/FlagsH#7]
The crouch-place mechanic seems to make it impossible to place non-flag banners on gates, chests, any switchable block.

Possible easy fix would be to simply NOT place flags on switchable blocks, just default banners.  That use case is more likely(?).

A step up... perhaps crouch-place on a switchable block gives a flag but... Shift-B-Click gives a banner (let Shift-F-Click work for symmetry).

**Comment by HydrolienF** [comment]
Thanks for sharing this request.
I will try to make it possible to place banner and flags on switchable blocks.

**Comment by HydrolienF** [comment]
I have finally have an idea to make banner placeable on switchable blocks without making flags unplaceable.

There is a new config option in the last release that allow to invert flags and banners placements when item is in offhand.
So you will be able to place a banner or a flag in sneak on a switchable using one hand or the other.

Update to 4.1.0 and set `offHandMod: INVERTED` in your config file.

![2024-06-25_11 51 32](https://github.com/HydrolienF/FlagsH/assets/71718798/1e351160-7481-44d4-b1bd-8d0a9228ee6f)

I'm closing the issue, but let me know if something doesn't work as expected or just if it works !
