### ISSUE TITLE
Banners can't be removed 

### ISSUE THREAD

**Issue by bruhhhwarrior** [HydrolienF/FlagsH#9]
Hello,
I tried to remove the banners using the commands but they did not work.
I later uninstalled the plugin and now I'm not sure what command to use or how to remove these banners.

Other than that this is a very cool plugin btw

**Comment by HydrolienF** [comment]
Hi, thanks for reporting that.
I'm glad that you enjoy the plugin and I will try to help you.

To remove it with the plugin, you should do `/flagsh remove 1` or `/flagsh remove all`. `/flagsh remove` should print all possible id of flags to remove. Or you can remove banner by hitting them.
If you removed `plugins/FlagsH/` the entities representing the flags aren't referenced by the plugin anymore, so it won't be able to remove it.

If you have removed the plugin, you can still remove the entity that represent the flags using Minecraft command:
- `/kill @e[type=Interaction]` will remove the flags hitbox in loaded chunks.
- `/kill @e[type=ItemDisplay]`wil remove the flag texture in loaded chunks.
If you use other plugin with item display or interaction, it will remove there interaction to. Add a radius parameter to the `/kill` to avoid that.

**Comment by bruhhhwarrior** [comment]
thank you!

**Comment by HydrolienF** [comment]
I'm closing the issue, but if you have other issue let me know.

**Comment by 404forever1** [comment]
![image](https://github.com/HydrolienF/FlagsH/assets/168977890/0e79b15a-8f6c-44af-bff3-8cb0ad9bcf88)

**Comment by 404forever1** [comment]
folia ，cant remove

**Comment by HydrolienF** [comment]
Have you try hitting the flag before using kill command ?
If you are on the same chunk of the interaction / display entity it should work. If it's not working with vanilla command, open a tiquet on [Folia](https://github.com/PaperMC/Folia)

**Comment by 404forever1** [comment]
> 在使用 kill 命令之前，您是否尝试过点击标志？ 如果您在交互/显示实体的同一块上，它应该可以工作。如果它不适用于 vanilla 命令，请在[Folia上打开一个问题](https://github.com/PaperMC/Folia)

Cannot be selected and there are no entities.

**Comment by HydrolienF** [comment]
If there is no `Interaction` and no `ItemDisplay`, then there is no more banner.

**Comment by 404forever1** [comment]
![b0f3a0b102d1d1af02677e0b02b5b070](https://github.com/HydrolienF/FlagsH/assets/168977890/4f19afde-fbbe-4955-9f42-482214f6259c)
He can't be chosen at all, but he's there.
